### ISSUE TITLE
Possible issue with 'load iff' and backward compatibility

### ISSUE THREAD

**Issue by huggy70** [AmiDARK/Amos-Professional-AGA-Releases#7]
When I try load an image with a height that is greater than the actual screen height I will get an error.

In old amos pro the picture gets loaded up to the height of the screen. Additional data in the file then will be ignored. This might break some old programs. This is only a small issue but as we cannot expect any program to be updated and so won't run

**Comment by AmiDARK** [comment]
With original Amos Professional when you use :
Load Iff "IMAGE.IFF", SCREENID : It automatically closes screen and reopen it to makes the full image being loaded
Load Iff "IMAGE.IFF" : The current screen is used and if image is wider, you receive a generic error message : "Can't fit picture in current screen"

When I try with Amos Professional AGA, I get the same result than with the original Amos Professional, excepted that now, I have inserted more precise error message like : "IFF/ILBM width is higher than the screen one".

https://user-images.githubusercontent.com/10142235/103378689-74a60100-4ae3-11eb-8260-5be3ffbe770a.mp4

**Comment by AmiDARK** [comment]
With all these, I close this issue.

**Comment by huggy70** [comment]
In my case Amos original will allow loading files with bigger format without screen number, so this might break some programs. Please have a look at example. Thx!

https://user-images.githubusercontent.com/76788005/103406002-67c3f480-4b59-11eb-9e2a-e7885bc7e34e.mp4

https://user-images.githubusercontent.com/76788005/103406006-6abee500-4b59-11eb-9229-a2ee3daebeae.mp4

**Comment by AmiDARK** [comment]
Hello,

I see this but the main problem resides in the Amos Professional source code. I uses the one from Marc365 repository. And official Francois Lionet source code is also from Marc365 repository.
If your Amos Professional version is compiled with a version we don't have the source code ... I don't have access to the changes you have in your version from my version (based on Marc365 version same as Francois Lionet repo).
I'll see that but don't promise anything.

**Comment by huggy70** [comment]
Hi,

thx fro reply!
I detected this when trying to run an old program I did 26 years ago. Back then, this was done with latest official release of AmosPro 2 with original license I bought. The version I testet with now I don't know where the source came from (it's not my original copy) but behaves exactly the same. Keep on the good work ! Looks promising.

**Comment by AmiDARK** [comment]
I think the source that were released were from a backup ... and probably not the latest version used for the original license...
